name: Verify branch name

on:
  push:
    branches-ignore: [main, production]

jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '(NANO-[0-9]+)[a-z0-9._-]+$'
          allowed_prefixes: 'NANO-/'
          ignore: main,production
          max_length: 30